version: "3.8"
services:
  olivetin:
    build: .
    container_name: olivetin
    volumes:
      - /docker/olivetin:/config # replace host path or volume as needed
    ports:
      - "1337:1337"
    restart: unless-stopped

networks:
  web: # should match the network defined under the container's networks
  section:
      external: true
