version: "3.8"
services:
  webui:
    build:
      context: ./webui
      args: # from env_file
        IMAGE_REPOSITORY: ${IMAGE_REPOSITORY}
        PROXY_USER: ${PROXY_USER}
        PROXY_PASSWORD: ${PROXY_PASSWORD}
        PROXY_FQDN: ${PROXY_FQDN}
        PROXY_PORT: ${PROXY_PORT}
    container_name: olivetin-webui
    restart: unless-stopped    
    env_file:
      - .env
    ports:
      - "1337:1337"
    volumes:
      - /docker/olivetin:/config # replace host path or volume as needed
    labels:
      - traefik.http.routers.olivetin.rule=Host(`run.your.domain`)
      - traefik.http.routers.olivetin.tls.certresolver=lets-encrypt

networks:
  web: # should match the network defined under the container's networks
  section:
      external: true
